pull_request_rules:
  - name: Renovate
    conditions:
      - author=renovate[bot]
      - check-success=Terraform Cloud/shunkakinoki/main
      - check-success=check
    actions:
      merge:
        method: merge
