pull_request_rules:
  - name: Automatic Merge for gitHub-actions[bot] Pull Requests
    conditions:
      - author=github-actions[bot]
      - status-success=WIP
    actions:
      merge:
        method: merge
