pull_request_rules:
  - name: Automatic Merge for Pull Requests
    conditions:
      - base=master
    actions:
      delete_head_branch:
        force: true
      merge:
        method: merge
        strict: true
