name: Auto-Approve
on:
  pull_request:
    types: [labeled]
jobs:
  auto-approve:
    if: github.actor == 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repository Contents
        uses: actions/checkout@master

      - name: Trigger on PR Label
        id: label
        run: python gha/validate_payload.py
        env:
          TRIGGER_LABEL_NAME: "Auto PR"

      - uses: hmarr/auto-approve-action@master
        if: steps.label.outputs.TRIGGERED == 'true'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  auto-merge:
    needs: [auto-approve]
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          LABELS: "!wip"
          AUTOMERGE: "Auto PR"
          MERGE_METHOD: "merge"
          MERGE_FORKS: "false"
          COMMIT_MESSAGE_TEMPLATE: "automatic"
