name: Build
on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "package.json"
      - "yarn.lock"
  pull_request:
    paths:
      - "src/**"
      - "package.json"
      - "yarn.lock"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Cache node modules
        id: cache
        uses: actions/cache@preview
        with:
          path: node_modules
          key: node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-
      - name: Install dependencies with yarn
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn install
      - name: Build Vuepress Site
        run: |
          yarn run build
      - name: Label on PR
        uses: awact/label-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "gha-build"
