name: Build
on:
  pull_request:
    paths:
      - "package.json"
      - "yarn.lock"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          cd $GITHUB_WORKSPACE
          yarn install
          yarn run build
      - name: Label on PR
        uses: awact/label-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "gha-build"
