name: Code Coverage
on:
  push:
    branches:
      - master
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@master
        with:
          token: ${{secrets.CODECOV_TOKEN}}
