name: Update
on:
  schedule:
    - cron: "*/3 * * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from Repository
        id: checkout
        uses: actions/checkout@v1
      - name: Checkout from shunkakinoki
        uses: actions/checkout@v1
        with:
          path: tmp
          repository: shunkakinoki/shunkakinoki
          ref: master
      - name: Copy Repository Contents
        run: |
          mkdir /home/runner/work/journal/tmp/.vuepress
          cp -a $GITHUB_WORKSPACE/src/.vuepress/. /home/runner/work/journal/tmp/.vuepress/
          rsync -aqu --delete /home/runner/work/journal/tmp/src/ $GITHUB_WORKSPACE/src
          mkdir $GITHUB_WORKSPACE/src/.vuepress
          cp -a /home/runner/work/journal/tmp/.vuepress/. $GITHUB_WORKSPACE/src/.vuepress/
      - name: Set Output Variables
        id: vars
        run: |
          echo ::set-output name=pr_title::"Sync Github Repo $(date +%d-%m-%Y)"
          echo ::set-output name=pr_body::"@shunkakinoki \
            This PR was auto-generated on $(date +%d-%m-%Y) \
            by [create-pull-request](https://github.com/peter-evans/create-pull-request)."
      - name: Create a Pull Request if Updated
        uses: peter-evans/create-pull-request@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          author-email: shunkakinoki@gmail.com
          author-name: Shun Kakinoki
          title: ${{ steps.vars.outputs.pr_title }}
          body: ${{ steps.vars.outputs.pr_body }}
          assignees: shunkakinoki
          reviewers: shunkakinoki
          branch: sync
          branch-suffix: short-commit-hash
