name: Update
on:
  schedule:
    - cron: "*/3 * * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from repo
        uses: actions/checkout@v2
        with:
          path: journal
      - name: Checkout from shunkakinoki
        uses: actions/checkout@v2
        with:
          path: shunkakinoki
          ref: master
          repository: shunkakinoki/shunkakinoki
      - name: Copy src directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/tmp/.vuepress
          cp -a $GITHUB_WORKSPACE/journal/src/.vuepress/. $GITHUB_WORKSPACE/tmp/.vuepress/
          rsync -aqu --delete $GITHUB_WORKSPACE/shunkakinoki/src/ $GITHUB_WORKSPACE/journal/src
          cp -a $GITHUB_WORKSPACE/tmp/.vuepress/. $GITHUB_WORKSPACE/journal/src/.vuepress/
          cd $GITHUB_WORKSPACE/journal
          git config --global user.name 'GitHub'
          git config --global user.email 'noreply@github.com'
          git add -A && git commit -m "perf(update) auto journal pr" || true
      - name: Set output variables
        id: vars
        run: |
          echo ::set-output name=pr_title::"Sync Github Repo $(date +%d-%m-%Y)"
          echo ::set-output name=pr_body::"@shunkakinoki \
            This PR was auto-generated on $(date +%d-%m-%Y) \
            by [create-pull-request](https://github.com/peter-evans/create-pull-request)."
      - name: Create a pull request if updated
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          committer: Shun Kakinoki <shunkakinoki@gmail.com>
          author: Shun Kakinoki <shunkakinoki@gmail.com>
          title: ${{ steps.vars.outputs.pr_title }}
          body: ${{ steps.vars.outputs.pr_body }}
          path: journal
