name: Update
on:
  schedule:
    - cron: "*/3 * * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from repo
        uses: actions/checkout@v2
        with:
          path: journal
      - name: Checkout from shunkakinoki
        uses: actions/checkout@v2
        with:
          path: shunkakinoki
          ref: master
          repository: shunkakinoki/shunkakinoki
      - name: Copy src directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/tmp/.vuepress
          cp -a $GITHUB_WORKSPACE/journal/src/.vuepress/. $GITHUB_WORKSPACE/tmp/.vuepress/
          rsync -aqu --delete $GITHUB_WORKSPACE/shunkakinoki/journal/ $GITHUB_WORKSPACE/journal/src
          cp -a $GITHUB_WORKSPACE/tmp/.vuepress/. $GITHUB_WORKSPACE/journal/src/.vuepress/
          cd $GITHUB_WORKSPACE/journal
      - name: Set output variables
        id: vars
        run: |
          echo ::set-output name=pr_title::"Sync Github Repo $(date +%d-%m-%Y)"
          echo ::set-output name=pr_body::"This PR was auto-generated on $(date +%d-%m-%Y)"
      - name: Create a pull request if updated
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          author: Shun Kakinoki <shunkakinoki@gmail.com>
          committer: Shun Kakinoki <shunkakinoki@gmail.com>
          commit-message: "perf(update): auto journal pr"
          title: ${{ steps.vars.outputs.pr_title }}
          body: ${{ steps.vars.outputs.pr_body }}
          path: journal
        env:
          HUSKY_SKIP_HOOKS: 1
